### ISSUE TITLE
Clean up default M-words data set

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#1]
- Remove incomplete Latin text (Val Max?)
- add one RtoL text

**Comment by Eumaeus** [comment]
What would be a very powerful demonstration would be some (scientific?) text in *three* versions: Greek, Arabic, English.

**Comment by neelsmith** [comment]
I'm going to remove messed up Latin texts, and add enough surahs of a Quran to be sure we total > 1M words.

**Comment by Eumaeus** [comment]
We've got a good one. I'm going to add Plutarch's Pericles in English.

**Comment by neelsmith** [comment]
Excellent. I'm happy to add another 1/4 million words of Latin when my boy has checked them out, but 800K is plenty good enough to announce 1.0 with in Croatia if that's what we've got in hand then!

**Comment by Eumaeus** [comment]
I think we're good. We have 1.16 million words of Greek, Arabic, Farsi, English, Latin, and German. Two biliingual texts, one trilingual text. Good licensing for all of them.

**Comment by Eumaeus** [comment]
I'm closing this for now.
