### ISSUE TITLE
"Explore texts" tab not showing all choices in menu

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#103]
Attaching full CEX catalog from a cex file with two texts.  In "Browse texts", both appear in the menu, and I can browse both.  In "Explore texts", however, only one of the two appears in the popup menu.

#!cexversion
3.0

#!citelibrary
name#HC Classics
urn#urn:cite2:cex:hc.2017_1:classics
license#CC Share Alike.  For details, see more info.

#!ctscatalog
urn#citationScheme#groupName#workTitle#versionLabel#exemplarLabel#online#lang
urn:cts:greekLit:tlg0016.tlg001.grc:#book/section#Herodotus#Histories#Greek, Godley, ed.##true#grc
urn:cts:greekLit:tlg0012.tlg001.allen:#book/line#Homeric Epic#Iliad#Greek. Allen, ed. Perseus Digital Library. Creative Commons Attribution 3.0 License##true#grc

**Comment by Eumaeus** [comment]
Reproduced with default "million.cex". I take it back… million.cex seems fine. Hmmm.

**Comment by Eumaeus** [comment]
Can't reproduce with any available CEX file. (Updated CiteApp to use latest libraries.) Tested with enlarged font-size in  browser, in case list-items were simply being hidden on the screen.

**Comment by Eumaeus** [comment]
Resolved. Working as expected, but an unclear UI.
