### ISSUE TITLE
n-gram search should be able to serarch for longest repeated ngram in the Iliad

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#126]
The pull-down menu limits you to a maximum value of 9 for n.  There are longer repeated n-grams in the Iliad.  We should find the longest n-gram occurring more than once, and support values of n at least equal to that in the pull down menu.

**Comment by Eumaeus** [comment]
Will fix for 1.4.4. This is easy.

**Comment by Eumaeus** [comment]
Bumped the max up to 15 with v.1.4.4
