### ISSUE TITLE
Export findings as 82xf

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/CITE-App#13]
We're all about scholarship, there should be ubiquitous "export findings" buttons for:

- grabbing the text you are looking at as 82xf.
- grabbing any generated list of URNs as 82xf.

Perhaps with an intial header-line, e.g.: 

    #Source: NGram URNs: threshold = 3; ignore-punctuation = true; queried on 'urn:cts:greekLit:tlg0016.tlg001.eng:'."

or

    #Source: urn:cts:greekLit:tlg0016.tlg001.eng:1.3-1.5

???

**Comment by Eumaeus** [comment]
[Best instructions for how to do downloads.](http://stackoverflow.com/questions/2897619/using-html5-javascript-to-generate-and-save-a-file)

[Actually… this is not really that helpful. But I think I know how to implement this, once we've decided on a format.]

**Comment by neelsmith** [comment]
Is 82xf superior to .cex?

My reasons for preferring .cex as first option:

1. integrate catalog and data
2. minimal but sufficient structure in ordered list or pairs for text data.

**Comment by neelsmith** [comment]
I think what you're really looking at here is an ORCA.

**Comment by Eumaeus** [comment]
CEX is not good for partial texts. If I have "found" (one way or another), `urn:cts:greekLit:tlg0012.tlg001.msA:1.611`, and want to save that as a fragment of an OHCO2 text, I want 82xf. I want:

- the urn (with hierarchy)
- the passage
- the prev and next (for "ordered")

If my NGram exploration produces 8 URNs, scattered throughout a text, I would like 8 82xf records.

Now… a CEX catalog section atop one-or-more 82xf records would be nice.

ORCA… surely that is way too much overhead for "I want to grab the stuff I just found"?

**Comment by neelsmith** [comment]
I agree we want to be able to export this, but I don't think we understand what it is we are exporting. 

We know how to cite a passage of text.  We know how to cite an ORCA reading of a text.  We don't know how to cite a search result.

**Comment by neelsmith** [comment]
Adding a "question" label because I think this issue implies the question: "What is the model of a search result?"

**Comment by neelsmith** [comment]
I think the question "What is a search result?" is important, and will if anything be even more urgent with CITE Collections.    I think we need to think this through very carefully before hacking up something we'll regret quickly.

**Comment by neelsmith** [comment]
Removing 1.1 milestone:important question, but not tied to 1.1 release.

**Comment by neelsmith** [comment]
Are we willing to consider closing this issue out, and focus instead on CEX export?

**Comment by Eumaeus** [comment]
Closing this for now.
