### ISSUE TITLE
Changing selection of current text should clear all display areas

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#15]
We have display areas for texts in two tabs (browse, explore). The two tabs share a notion of "current text" and each offers the chance to change that selection.

Displays should therefore be cooridnated:  changing the current text should empty out the text browsing display and search results display.

**Comment by Eumaeus** [comment]
They don't, though. The two tabs can have different current texts... you can Browse Cicero while doing NGrams on Herodotus.

The "Browse" panel only changes when you click on a passage-URN from the "URNs for NGram" list.

**Comment by neelsmith** [comment]
Well, at *least* contents on the given tab should be cleared when a new text is displayed then.   If you choose Herodotus as current text to browse or query, no CIcero should be left on the screen

**Comment by Eumaeus** [comment]
I can do that…

**Comment by Eumaeus** [comment]
Implemented it like that. Pushed!

**Comment by neelsmith** [comment]
Works on Explore Texts tab, but not in Browse Texts tab after I pull on the current version.  Reopening.

**Comment by Eumaeus** [comment]
So, clear text field when "current work" changes… I can do that.

**Comment by Eumaeus** [comment]
Done.

**Comment by Eumaeus** [comment]
Loading a new library should clear everything, too. Reopening

**Comment by Eumaeus** [comment]
Fixed that.
