### ISSUE TITLE
Increasing display size in "Explore" tab masks query input

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#16]
I can't readily read the default text size, so just used browser's "Zoom in" to magnify.    This resulted in the empy "N-Grams" display area overlapping the N-Gram and "Occurs" inputs in N-Gram Tools.  They were still legible at the default setting, but I could not change their value.

**Comment by neelsmith** [comment]
Was able to replicate this in Chrome and Safari (both on OS X)

**Comment by Eumaeus** [comment]
Yep... I need to work on this.

**Comment by Eumaeus** [comment]
I think I've fixed this. Tested at various magnifications, from "very large" to "Mr. Magoo".
