### ISSUE TITLE
Figure out how to display cataloged works that are *not* online

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#18]
TextRepositories support cataloging of notional works that are not included in the data set.  How should they appear in the list of works?  Just skip them if they're not online?  (Probably wisest for current version:  this is not intended to be a library cataloging app....)

**Comment by Eumaeus** [comment]
We can do this either way. It is easy to check for an "online" and *not* wrap the description in a "clickable_urn" span. If we eventually put detailed cataloging info in a CITE Collection, there won't be much point in showing not-online works in the "browse/explore online works" part.

**Comment by Eumaeus** [comment]
Since this is not a cataloging app, I think we can safely skip any recorded work that doesn't resolve to a Corpus of at least one Citable Node. I'm going to close this for now.
