### ISSUE TITLE
Prior to public release/announcement, make sure compiled SPA is current

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#19]

**Comment by Eumaeus** [comment]
And remove the final line of the compiled JS before inserting it into SPA, to avoid complains that the "js.map" file can't be found.

**Comment by neelsmith** [comment]
bumping this to 1.1 milestone since we're nearly in position to release that.

**Comment by neelsmith** [comment]
and don't merge 1.1 branch with master until this is resolved

**Comment by neelsmith** [comment]
Doesn't matter now if you just use `sbt spa` to build:  that first does a fullOptJS comiplation, then constucts the SPA from it.

Closing this on the assumption it's at least as likely we can remember to run `sbt spa` as it is we can do any other single action.
