### ISSUE TITLE
Version descriptions…

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/CITE-App#24]
We've got elaborate licensing info in the version-labels of our .cex files. This makes the sidebar really long, and is going to be a problem when we have larger texts. I guess I could do a fancy "hover" thingy, where only the first line or two shows by default untll you hover over it. But what do you think?

**Comment by Eumaeus** [comment]
I think  I have a good solution implemented in css. I'd like to keep fullsome labels in the `cex`.

**Comment by neelsmith** [comment]
I think what you've implemented is fine.  Close this?

**Comment by Eumaeus** [comment]
K.
