### ISSUE TITLE
Better version-level identifiers in URNs?

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#25]
For hdt, 'eng' and 'grc' are I think unfortunate choices for version identifiers.  'loebeng' or 'loebgrc' or the like might be better?

**Comment by Eumaeus** [comment]
I like it. I'll make the change and clear this when I have.

**Comment by Eumaeus** [comment]
Fixed, pushed into cts-demo-corpus. Updated in citeApp, committed but not pushed yet.
