### ISSUE TITLE
Name SPA with version number.

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#28]
E.g.,`cite-1.1.html`

**Comment by Eumaeus** [comment]
Leaving this open until we've merged and announced, since it (currently) has to be done by hand, every time.

**Comment by neelsmith** [comment]
Should create version-named file in 1.1 branch:  when it merges with master, it will be there.  We can allow successive versioned SPAs to accumulate in master with no extra effort in that way.

**Comment by Eumaeus** [comment]
I've added a 1.1.0 template to the build. We'll still have to manually add .css and .js to it, but this will save about five steps.

**Comment by neelsmith** [comment]
What is this "template"?  Where in the repo is it? Is it `src/main/resources/cite-1.1.0.html` ?

**Comment by neelsmith** [comment]
implemented : see #37
