### ISSUE TITLE
Add updated HMT normalized data set?

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#3]
Should this be a default example in *this* repo?

Or is it better placed elsewhere?

**Comment by Eumaeus** [comment]
I like the idea of having two example `.cex` libraries, one including a variety of texts, and HMT, as an example of a real, coherent body of data.

**Comment by neelsmith** [comment]
I'm going to move this to 1.1 milestone.  I also like the idea of having two example .cex libraries, but don't think we should make a 1.0 release hostage to that.

**Comment by neelsmith** [comment]
clearing milestone tag altogether. We can add it when we add it:  no need to tie releaeses to this data set when we've got a good 1M word sample loading by default.

**Comment by neelsmith** [comment]
Renaming the hmt file to a more accurate name, since it only has hmt scholia.

Closing this out:  we've got this checked in to master, no issue really remaining.
