### ISSUE TITLE
LICENSE file in compiled app directory is out of date

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#40]
Accurate license file in cts-demo repository?  Is that collection stable enough for a given version that we should just replicate the license file in this repo (rather than point to it remotely)?

I would strongly prefer to keep a c opy of the license file directly in this directory.

**Comment by Eumaeus** [comment]
I will get on this

**Comment by Eumaeus** [comment]
The license file in cts-demo is up-to-date, and I've copied it into the Downloads directory.
