### ISSUE TITLE
Consider factoring out URL for default CEX file.

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#43]
If this were a build setting, then someone could build a CITE App for their individual project by:

1. changing the value for default CEX in `build.sbt`
2. running `sbt spa`

and an html file loading their project data *by default* will appear in the downloads directory.

**Comment by Eumaeus** [comment]
I will work on this in the 1.2 branch

**Comment by neelsmith** [comment]
Actually, it ought to be straightforward:  I realized that value is actually in the HTML template file, not generated by scala code.  I could probably add that to the spa task easily if I could sort out setting sbt properties properly...

**Comment by neelsmith** [comment]
I this we should allow the separator to be specified in the call to CiteMainController, as elsewhere.  At present, it looks like the value for delimiter is always  read by the loadLocalLibrary function from the file picker.  

Alternatively, I suppose we could have a setting determining what delimiter to make the default for the file picker.  

In any event, if we're going to permit defining the default CEX source, we need to be able to express how it's delimited.

**Comment by neelsmith** [comment]
See comments on why this suggestion is a good thing in #45

**Comment by Eumaeus** [comment]
Done as of 1.2.1. Library URL, and its delimiter, are paramterized in `build.sbt` and show up in the results of a `sbt spa` build.
