### ISSUE TITLE
What does it take to alter default CEX source?

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#44]
I've built CITE App with default source URLs on both shot.holycross.edu and beta.hpcc.uh.edu, and have in both cases been unable to load the file, even though I can load the same file locally and get a usable corpus.

??

Is CITE-App expecting something in HTTP headers?  Response type, e.g.?

We definitely want to be able to build this for default sources that are just spitting text at you.  Not sure what else I could be doing wrong.  Char encoding, so that nl not reocginzed???

**Comment by neelsmith** [comment]
This all looks good ...


![headers](https://cloud.githubusercontent.com/assets/2204294/24925953/f31ff474-1ec7-11e7-83e0-3454eda8906d.png)

**Comment by neelsmith** [comment]
Whereasw this is what github produces:

![ghheaders](https://cloud.githubusercontent.com/assets/2204294/24926060/521af082-1ec8-11e7-95b9-5ee0e1beb562.png)

**Comment by neelsmith** [comment]
So it's neither content type nor text encoding.

Is CITE App expecting https ????

If so, I think that's a bug.

**Comment by Eumaeus** [comment]
I am not good at, nor have I found good docs for, http-request in Scala-JS. Nor have I ever been au courant with the intricacies of headers, cross-domain requests, and all that. Now that https is a thing, I am even more hopeless. I think we should close this, eschew remote loading of .cex files for now, and await microservices, which we know we are good at.

**Comment by neelsmith** [comment]
The answer is that different browsers treat http and https requests differently: Chrome sees it as violating cross-brwoser request policy when you ask for http data from local file; Safari does not.  

Related questions are still open in #43 and #45, but i think this issue has been resolved, so closing.
