### ISSUE TITLE
Do away with auto-loading of remote .cex files?

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/CITE-App#45]
We will eventually have a microservice. This is the "two-file App".

**Comment by neelsmith** [comment]
I would like to restore autoloading and building with a definable default CEX. This is good for the following circumstances:


1. You want default cex to be availalbe from an HTTPS source.  As far as I can tell, all browsers accept this any time, so any copy of your app works anywhere, just as you originally did in 1.1.
2. You want default cex to be available fro plain http.  In that case, to avoid cross-browser issues, you install your (presumably renamed) html file on the same server as the CEX, so no xbrowser problems.  This is great for (for example) installing an HMT scholia browser or HMT Iliad browser on a houston machine.  If someone downloads that particular HTML file and tries to run locally, results will depend on your browser's behavior regarding http requests in the app.
3. You want to run offline.  No change.

So I think all situations are good, and worth supporting.

**Comment by neelsmith** [comment]
So my view on this is still consistent with suggestion in #43

**Comment by Eumaeus** [comment]
As of v.1.2.1, you can:

- Define a defaultLibraryURL and defaultLibraryDelimiter in `build.sbt`, and have those reflected in the SPA, after a `sbt spa` build.
- Get the error code for any failed Ajax call to that library (404, etc.)

I'm going to close this for now.
