### ISSUE TITLE
Use Catalog from TextRepository to find labels for citation scheme?

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#8]
Not assigned a milestone.  Open question for future inclusion/rejection.

**Comment by neelsmith** [comment]
Perhaps best included in list of works, not intrusively displayed where retrieve passage is shown?

**Comment by Eumaeus** [comment]
Done. I'm only showing this on "Works in this Corpus" list on the Browse page, not the "Explore" page. Looks good!
