### ISSUE TITLE
Frequent off-by-one error in display of n-gram results

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#98]
Regularly, but not it seems universally, the number of matching n-grams shown in the "Explore texts" tab is one fewer than the number retrieved by following the link to the list of passages.

This running the current 1.2.1 release.

I have a test CEX file of Lysias 1 and can specify some example n-gram results that illustrte the problem if that would be helpful.

**Comment by Eumaeus** [comment]
Closing since OHCO2 10.4.0
