### ISSUE TITLE
More generally, all n-gram results are nonsensical

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CITE-App#99]
Obviously, n-gram of 1 occurring minimum of 1 time should be a complete vocabulary list of a text.

Only a tiny fraction of the vocabulary shows up for a query like this.  

Another demonstration:  ngram filtering by words pasted in from retrieving a passage that produces no results.

Most likely a problem in the underlying ohco2 library?

Until the source of this issue is identified, corrected and tested thoroughly, no results of n-gram searching should ever be used for anything.

**Comment by neelsmith** [comment]
Compiled CITE-App with updates to current versions of library dependencies, but n-gram results are still weird.

**Comment by Eumaeus** [comment]
Closing for now.
